/**
 * E2E tests for the Refine page.
 *
 * Tests use the E2E mock layer (TAURI_E2E=true) to replace Tauri
 * commands with in-memory responses. Agent lifecycle events are
 * dispatched through the agent simulator, exercising the same code
 * paths the real sidecar would trigger.
 *
 * The refine page gets its agentId from the `send_refine_message`
 * mock response (generated by the backend). Tests read the agentId
 * from the rendered `data-agent-id` attribute on the thinking
 * indicator / agent turn element.
 */
import { test, expect, type Page } from "@playwright/test";
import { simulateAgentRun, simulateAgentError } from "../helpers/agent-simulator";
import {
  navigateToRefine,
  navigateToRefineWithSkill,
} from "../helpers/refine-helpers";

/**
 * After clicking send, wait for the thinking indicator then read the
 * dynamically-generated agent ID from the DOM.
 */
async function getAgentId(page: Page): Promise<string> {
  const thinking = page.getByTestId("refine-agent-thinking");
  await thinking.waitFor({ timeout: 5_000 });
  const agentId = await thinking.getAttribute("data-agent-id");
  if (!agentId) throw new Error("Could not read agent ID from thinking indicator");
  return agentId;
}

test.describe("Refine Page", { tag: "@refine" }, () => {
  test("shows skill picker and placeholder when no skill selected", async ({ page }) => {
    await navigateToRefine(page);

    // Skill picker shows placeholder
    await expect(page.getByRole("button", { name: /Select a skill/ })).toBeVisible();

    // Chat panel shows no-skill prompt
    await expect(page.getByTestId("refine-no-skill")).toBeVisible();
    await expect(page.getByTestId("refine-no-skill")).toContainText(
      "Select a skill to start refining",
    );

    // Preview panel shows no-skill prompt
    await expect(page.getByTestId("refine-preview-empty")).toBeVisible();
    await expect(page.getByTestId("refine-preview-empty")).toContainText(
      "Select a skill to preview its files",
    );
  });

  test("auto-selects skill from search param and loads files", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // Skill picker shows the selected skill name
    await expect(page.getByText("Test Skill").first()).toBeVisible();

    // Preview panel file picker shows SKILL.md (first file)
    await expect(page.getByTestId("refine-file-picker")).toContainText("SKILL.md");

    // Chat input is enabled
    await expect(page.getByTestId("refine-chat-input")).toBeEnabled();

    // Chat shows empty state (no messages yet)
    await expect(page.getByTestId("refine-chat-empty")).toBeVisible();
  });

  test("skill picker dropdown shows available skills", async ({ page }) => {
    await navigateToRefine(page);

    // Open skill picker
    await page.getByRole("button", { name: /Select a skill/ }).click();

    // Both skills should be visible in the dropdown
    await expect(page.getByRole("option", { name: /test-skill/ })).toBeVisible();
    await expect(page.getByRole("option", { name: /analytics-skill/ })).toBeVisible();

    // Select test-skill
    await page.getByRole("option", { name: /test-skill/ }).click();

    // Skill picker now shows the skill name
    await expect(page.getByText("test-skill").first()).toBeVisible();

    // Preview panel should load — file picker shows SKILL.md
    await expect(page.getByTestId("refine-file-picker")).toContainText("SKILL.md");
  });

  test("send a refine message and see agent response", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // Type a message
    const input = page.getByTestId("refine-chat-input");
    await input.fill("improve the intro section");

    // Send
    await page.getByTestId("refine-send-button").click();

    // User message appears in chat
    await expect(page.getByText("improve the intro section")).toBeVisible();

    // Read the dynamically-generated agent ID from the thinking indicator
    const agentId = await getAgentId(page);

    // Simulate agent run
    await simulateAgentRun(page, {
      agentId,
      messages: [
        "Reading SKILL.md...",
        "I've updated the introduction to be more concise and actionable.",
      ],
      result: "Refinement complete.",
    });

    // Agent messages appear
    await expect(
      page.getByText("I've updated the introduction to be more concise and actionable."),
    ).toBeVisible();

    // Thinking indicator is gone (agent has messages now, or has exited)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
  });

  test("slash command /rewrite shows badge and sends command", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");

    // Type "/" to trigger command picker
    await input.press("/");
    await page.waitForTimeout(100);

    // Command picker should open with both options
    await expect(page.getByText("Rewrite skill")).toBeVisible();
    await expect(page.getByText("Validate skill")).toBeVisible();

    // Select "Rewrite skill"
    await page.getByText("Rewrite skill").click();

    // /rewrite badge should appear
    await expect(page.getByTestId("refine-command-badge")).toBeVisible();
    await expect(page.getByTestId("refine-command-badge")).toContainText("/rewrite");

    // Type additional instructions
    await input.fill("improve structure");

    // Send
    await input.press("Enter");

    // User message in chat should show the /rewrite badge
    await expect(page.getByText("/rewrite").last()).toBeVisible();

    // Read agentId and simulate agent
    const agentId = await getAgentId(page);
    await simulateAgentRun(page, {
      agentId,
      messages: ["Rewriting skill with improved structure..."],
      result: "Rewrite complete.",
    });

    await expect(page.getByText("Rewriting skill with improved structure...")).toBeVisible();
  });

  test("slash command /validate with no text sends correctly", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");

    // Type "/" to trigger command picker
    await input.press("/");
    await page.waitForTimeout(100);

    // Select "Validate skill"
    await page.getByText("Validate skill").click();

    // /validate badge should appear
    await expect(page.getByTestId("refine-command-badge")).toBeVisible();
    await expect(page.getByTestId("refine-command-badge")).toContainText("/validate");

    // Send with no text (just the command)
    await page.getByTestId("refine-send-button").click();

    // Should see the /validate badge in chat history (no empty bubble)
    await expect(page.getByText("/validate").last()).toBeVisible();

    // Read agentId and simulate agent
    const agentId = await getAgentId(page);
    await simulateAgentRun(page, {
      agentId,
      messages: ["Validating skill files..."],
      result: "Validation complete. No issues found.",
    });

    await expect(page.getByText("Validating skill files...")).toBeVisible();
  });

  test("@file targeting shows file badge", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");

    // Type "@" to trigger file picker
    await input.press("@");
    await page.waitForTimeout(100);

    // File picker should show available files — use role="option" to target picker items
    await expect(page.getByRole("option", { name: "SKILL.md" })).toBeVisible();
    await expect(page.getByRole("option", { name: "references/glossary.md" })).toBeVisible();

    // Select SKILL.md via the picker option (role="option")
    await page.getByRole("option", { name: "SKILL.md" }).click();

    // @SKILL.md badge should appear — scoped to the input bar badges area
    // The Badge component renders with data-slot="badge" and data-variant="secondary"
    const badgeArea = page.locator("[data-slot='badge'][data-variant='secondary']", { hasText: "@SKILL.md" });
    await expect(badgeArea.first()).toBeVisible();

    // Type a message and send
    await input.fill("fix the intro");
    await input.press("Enter");

    // User message should show SKILL.md badge in the chat
    await expect(page.getByText("SKILL.md").last()).toBeVisible();
  });

  test("preview panel file picker switches files", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // Initially shows SKILL.md
    await expect(page.getByTestId("refine-file-picker")).toContainText("SKILL.md");

    // Open file picker
    await page.getByTestId("refine-file-picker").click();

    // Should show both files
    await expect(page.getByRole("option", { name: /SKILL\.md/ })).toBeVisible();
    await expect(page.getByRole("option", { name: /references\/glossary\.md/ })).toBeVisible();

    // Select glossary
    await page.getByRole("option", { name: /references\/glossary\.md/ }).click();

    // File picker should now show glossary
    await expect(page.getByTestId("refine-file-picker")).toContainText("references/glossary.md");
  });

  test("diff toggle button disabled when no baseline", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // Diff toggle should exist but be disabled (no baseline snapshot)
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeVisible();
    await expect(diffToggle).toBeDisabled();
  });

  test("happy path: select skill, send message, see agent output, verify diff", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // --- 1. Verify skill loaded ---
    await expect(page.getByText("Test Skill").first()).toBeVisible();
    await expect(page.getByTestId("refine-file-picker")).toContainText("SKILL.md");

    // --- 2. Send a refinement message ---
    const input = page.getByTestId("refine-chat-input");
    await input.fill("add a quick-start section");
    await page.getByTestId("refine-send-button").click();

    // User message visible in chat
    await expect(page.getByText("add a quick-start section")).toBeVisible();

    // --- 3. Get agent ID from thinking indicator ---
    const agentId = await getAgentId(page);

    // --- 4. Swap mock to return modified files (simulates agent edits) ---
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
    });

    // --- 5. Simulate agent run ---
    await simulateAgentRun(page, {
      agentId,
      messages: [
        "Reading SKILL.md...",
        "Added a Quick Start section with getting-started steps.",
      ],
      result: "Refinement complete.",
    });

    // --- 6. Verify agent output appears ---
    await expect(
      page.getByText("Added a Quick Start section with getting-started steps."),
    ).toBeVisible();

    // Thinking indicator gone
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();

    // --- 7. Verify diff toggle is now enabled (baseline was snapshotted) ---
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();

    // --- 8. Toggle diff mode ---
    await diffToggle.click();

    // Button label should switch to "Preview" (indicating diff mode is on)
    await expect(diffToggle).toContainText("Preview");

    // --- 9. Verify diff shows the changes ---
    // The added "Quick Start" section should appear as added lines (green, + prefix)
    await expect(page.locator("text=+ ## Quick Start")).toBeVisible();
    await expect(page.locator("text=+ Get started in 3 steps.")).toBeVisible();
  });

  test("multi-turn refinement: second turn diff shows only that turn's changes", async ({ page }) => {
    // --- Turn 1: Add Quick Start section ---
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("add a quick-start section");
    await page.getByTestId("refine-send-button").click();

    const agentId1 = await getAgentId(page);

    // Swap mock to return SKILL.md with Quick Start added
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
    });

    await simulateAgentRun(page, {
      agentId: agentId1,
      messages: ["Adding quick-start section..."],
      result: "Done.",
    });

    // Wait for agent to finish and files to reload (updateSkillFiles is async)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
    await page.locator("text=Quick Start").first().waitFor();

    // Verify turn 1 diff
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await diffToggle.click();
    await expect(page.locator("text=+ ## Quick Start")).toBeVisible();
    await diffToggle.click(); // Toggle diff off

    // --- Turn 2: Add Tips section ---
    // Swap send_refine_message mock to return a new agent ID for turn 2
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.send_refine_message = "refine-test-skill-e2e-002";
    });

    await input.fill("add a tips section");
    await page.getByTestId("refine-send-button").click();

    const agentId2 = await getAgentId(page);
    expect(agentId2).toBe("refine-test-skill-e2e-002");

    // Swap mock to return SKILL.md with BOTH Quick Start AND Tips
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Tips\n\nRemember to test often.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
    });

    await simulateAgentRun(page, {
      agentId: agentId2,
      messages: ["Adding tips section..."],
      result: "Done.",
    });

    // Wait for agent to finish
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();

    // Verify turn 2 diff shows only turn 2 changes
    await diffToggle.click();
    await expect(page.locator("text=+ ## Tips")).toBeVisible();
    await expect(page.locator("text=+ Remember to test often.")).toBeVisible();

    // Quick Start was already in baseline for turn 2, should NOT appear as added
    await expect(page.locator("text=+ ## Quick Start")).not.toBeVisible();
  });

  test("multi-file diff: switching files shows per-file changes", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("improve both files");
    await page.getByTestId("refine-send-button").click();

    const agentId = await getAgentId(page);

    // Swap mock to return both files modified
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        {
          path: "references/glossary.md",
          content: "# Glossary\n\n- **Term**: Definition\n- **New Term**: New definition",
        },
      ];
    });

    await simulateAgentRun(page, {
      agentId,
      messages: ["Updating both files..."],
      result: "Done.",
    });

    // Wait for agent to finish and files to reload (updateSkillFiles is async)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
    await page.locator("text=Quick Start").first().waitFor();

    // Toggle diff on — SKILL.md is the active file
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await diffToggle.click();
    await expect(page.locator("text=+ ## Quick Start")).toBeVisible();

    // Switch to glossary file
    await page.getByTestId("refine-file-picker").click();
    await page.getByRole("option", { name: /references\/glossary\.md/ }).click();

    // Verify glossary diff shows glossary-specific changes
    await expect(page.locator("text=+ - **New Term**: New definition")).toBeVisible();

    // Verify glossary diff does NOT show SKILL.md-only changes
    await expect(page.locator("text=+ ## Quick Start")).not.toBeVisible();
  });

  test("agent error mid-refine: error renders, chat usable, diff preserved", async ({ page }) => {
    // --- Turn 1 (successful): Add Quick Start section ---
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("improve intro");
    await page.getByTestId("refine-send-button").click();

    const agentId1 = await getAgentId(page);

    // Swap mock to return modified SKILL.md with Quick Start
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
    });

    await simulateAgentRun(page, {
      agentId: agentId1,
      messages: ["Improving intro..."],
      result: "Done.",
    });

    // Wait for agent to finish and files to reload (updateSkillFiles is async)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
    await page.locator("text=Quick Start").first().waitFor();

    // Verify diff toggle enabled and turn 1 diff works
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(page.locator("text=+ ## Quick Start")).toBeVisible();
    await diffToggle.click(); // Toggle diff off

    // --- Turn 2 (error): Agent fails before modifying files ---
    // Swap send_refine_message mock to return a new agent ID
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.send_refine_message = "refine-error-e2e-001";
    });

    // Do NOT change get_skill_content_for_refine mock (agent fails before modifying files)
    await input.fill("add more content");
    await page.getByTestId("refine-send-button").click();

    const agentId2 = await getAgentId(page);
    expect(agentId2).toBe("refine-error-e2e-001");

    // Simulate agent error (init_start → sdk_ready → exit with success=false)
    await simulateAgentError(page, agentId2);

    // Verify error toast
    await expect(page.getByText("Agent failed — check the chat for details").first()).toBeVisible();

    // Verify chat input is still enabled (user can retry)
    await expect(page.getByTestId("refine-chat-input")).toBeEnabled();

    // Verify diff toggle is still enabled (baseline exists from turn 1)
    await expect(diffToggle).toBeEnabled();

    // Toggle diff on — should show NO added lines because baseline was
    // re-snapshotted to post-turn-1 state and files are still in post-turn-1 state
    await diffToggle.click();
    await expect(page.locator("text=+ ## Quick Start")).not.toBeVisible();
  });
});
